version: 2.1

jobs:

  lint:
    docker:
      - image: golang:1.14-stretch
    steps:
      - checkout
      - run:
          name: Prepare environment
          command: |
            wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.23.6
      - run:
          name: Check code formatting
          command: |
            export UNFORMATTED=`gofmt -l .`
            [ -z "$UNFORMATTED" ] && exit 0
            echo "Code not formatted, use gofmt for these files:"
            echo $UNFORMATTED
            exit 1
      - run:
          name: Lint code
          command: |
            ./bin/golangci-lint run

  test:
    docker:
      - image: golang:1.14-stretch
    steps:
      - checkout
      - run:
          name: Test code
          command: |
            go test --race ./...

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
